"""
Data models for the SportsSummaryAgent module.
"""

from datetime import date, datetime
from typing import Literal

from pydantic import BaseModel, Field, field_validator


class MatchResult(BaseModel):
    """Represents the result of a football match."""

    home_team: str = Field(description="Home team name")
    away_team: str = Field(description="Away team name")
    home_score: int = Field(ge=0, description="Home team score")
    away_score: int = Field(ge=0, description="Away team score")
    match_date: date = Field(description="Date of the match")
    competition: str = Field(
        default="La Liga", description="Name of the championship/tournament"
    )

    @field_validator("home_team", "away_team", mode="before")
    @classmethod
    def normalize_team_name(cls, v: str) -> str:
        """Normalize team names (strip whitespace, capitalize)."""
        return v.strip().title()

    @property
    def match_id(self) -> str:
        """Generate a unique identifier for the match."""
        home = self.home_team.lower().replace(" ", "-")
        away = self.away_team.lower().replace(" ", "-")
        return f"{home}-{away}-{self.match_date.isoformat()}"


class MatchSummary(BaseModel):
    """Match summary generated by AI with exactly 3 bullet points and championship context."""

    match_id: str = Field(description="Unique identifier of the match")
    bullet_points: list[str] = Field(
        min_length=3,
        max_length=3,
        description="Three key points of the match, each as a separate string",
    )
    championship_context: str = Field(
        description="Championship context: table position, implications, etc."
    )
    generated_at: datetime = Field(
        default_factory=datetime.now,
        description="Timestamp when the summary was generated",
    )
    model_used: str = Field(description="Language model used for generation")
    inference_source: Literal["local_ollama", "cloudflare_tunnel", "dry_run"] = Field(
        description="Source of the inference"
    )

    @field_validator("bullet_points", mode="before")
    @classmethod
    def ensure_three_bullet_points(cls, v: list[str]) -> list[str]:
        """Ensure exactly three bullet points."""
        if len(v) != 3:
            raise ValueError("Must have exactly three bullet points")
        return v
