name: Sincronizador Cule Diario

on:
  schedule:
    # Se ejecuta cada hora (00, 01, 02...) para mantener actualizadas las 
    # probabilidades a cada hora, y por consiguiente a las 6h, 3h, 2h y 1h antes del partido.
    - cron: '0 * * * *'
  workflow_dispatch: # Permite darle al botón de "Play" manual

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar script del Barça y Sincronizar Google Calendar
        env:
          GOOGLE_TOKEN_JSON: ${{ secrets.GOOGLE_TOKEN_JSON }}
        run: python bot_barca.py

      - name: Hacer commit y push (Pintar de verde)
        run: |
          git config --global user.name "Aleix Quirante"
          git config --global user.email "quirante70@gmail.com"
          git add log_partidos.md
          git commit -m "⚽ Barça Bot: Sincronización diaria completada $(date +'%Y-%m-%d')" || exit 0
          git push